name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Bump version and tag
        id: tag_version
        run: |
          echo "Fetching tags..."
          git fetch --tags
          git config user.name "GitHub Actions"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          VERSION=$(python setup.py --version)
          echo "Current version: $VERSION"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin --tags
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.tag_version.outputs.VERSION }}
          name: v${{ steps.tag_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distribution to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
