name: Publish Release

on:
  workflow_run:
    workflows: ["Release Drafter"]
    types:
      - completed

permissions:
  contents: write

jobs:
  publish_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Get Version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = 'v${{ steps.get_version.outputs.VERSION }}';
            const release_name = `Release ${tag}`;
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: release_name,
              draft: false,
              prerelease: false,
            });
